version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: organic-products-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: organicpassword123
      MONGO_INITDB_DATABASE: organic-products
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - organic-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: organic-products-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:organicpassword123@mongo:27017/organic-products?authSource=admin
      - JWT_SECRET=organic-products-super-secret-jwt-key-2024-production
      - JWT_EXPIRE=7d
      - FRONTEND_URL=http://localhost:3000
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=${EMAIL_USER:-your-email@gmail.com}
      - EMAIL_PASS=${EMAIL_PASS:-your-app-password}
      - OTP_EXPIRE_MINUTES=10
      - OTP_LENGTH=6
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - organic-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
    container_name: organic-products-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - organic-network

  # Redis for Session Storage (Optional - for future scaling)
  redis:
    image: redis:7-alpine
    container_name: organic-products-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - organic-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  organic-network:
    driver: bridge